In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

In [2]:
df = pd.read_csv("../WeatherPy/cities.csv")
df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,1,ovre ardal,61.32,7.80,66.2,48.0,40.0,4.70,NO,1.594828e+09
1,2,kapaa,22.08,-159.32,78.8,83.0,90.0,14.99,US,1.594828e+09
2,3,tagusao,9.19,117.81,81.0,78.0,8.0,4.34,PH,1.594828e+09
3,4,longyearbyen,78.22,15.64,48.2,61.0,75.0,5.82,SJ,1.594828e+09
4,5,moindou,-21.69,165.68,68.0,82.0,90.0,6.93,NC,1.594828e+09

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
locations = df[["Lat", "Lng"]]
weights = df["Humidity"]

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=weights, 
                                 dissipating=False, max_intensity=150,
                                 point_radius = 3)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
hotel_df = df.loc[(df["Max Temp"] < 80) & (df["Max Temp"] > 70) & (df["Wind Speed"] < 10) & (df["Cloudiness"] == 0)]
hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
156,172,fayaoue,-20.65,166.53,73.51,76.0,0.0,7.78,NC,1.594828e+09
257,277,oktyabrskiy,54.48,53.47,78.91,72.0,0.0,2.71,RU,1.594828e+09
277,299,la tuque,47.43,-72.78,74.19,43.0,0.0,5.55,CA,1.594828e+09
322,345,menongue,-14.66,17.69,73.22,18.0,0.0,7.40,AO,1.594828e+09
494,539,hushitai,41.93,123.51,75.20,88.0,0.0,4.47,CN,1.594828e+09

In [6]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {
    "radius": 5000,
    "keyword": "Hotel",
    "types": "Hotel",
    "key": g_key,
}

for index, row in hotel_df.iterrows():
    
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    response = requests.get(base_url, params=params).json()
    
    results = response['results']
    
    try:
        print(f"Closest Hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        hotel_df.loc[index, 'Hotel Lat'] = results[0]['geometry']['location']['lat']
        hotel_df.loc[index, 'Hotel Lng'] = results[0]['geometry']['location']['lng']

    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
         
    print("------------")

Closest Hotel is Hotel Beauprés; Ouvéa, Nouvelle-Calédonie.
------------

/Users/yingfeng/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/yingfeng/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Closest Hotel is Hotel Devon.
------------
Closest Hotel is Hôtel Marineau La Tuque.
------------
Closest Hotel is Ritz Lauca.
------------
Closest Hotel is Shenyang WanXi Tiantian Hotel.
------------

In [7]:
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Lat,Hotel Lng
156,172,fayaoue,-20.65,166.53,73.51,76.0,0.0,7.78,NC,1.594828e+09,"Hotel Beauprés; Ouvéa, Nouvelle-Calédonie",-20.624926,166.551861
257,277,oktyabrskiy,54.48,53.47,78.91,72.0,0.0,2.71,RU,1.594828e+09,Hotel Devon,54.481347,53.466940
277,299,la tuque,47.43,-72.78,74.19,43.0,0.0,5.55,CA,1.594828e+09,Hôtel Marineau La Tuque,47.392500,-72.784722
322,345,menongue,-14.66,17.69,73.22,18.0,0.0,7.40,AO,1.594828e+09,Ritz Lauca,-14.655517,17.684072
494,539,hushitai,41.93,123.51,75.20,88.0,0.0,4.47,CN,1.594828e+09,Shenyang WanXi Tiantian Hotel,41.952824,123.529040

In [8]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]
hotel_locations = clean_hotel_df[["Hotel Lat", "Hotel Lng"]]
markers = gmaps.marker_layer(hotel_locations)
symbol = gmaps.symbol_layer(hotel_locations, info_box_content=hotel_info)
fig.add_layer(markers)
fig.add_layer(symbol)
fig

Figure(layout=FigureLayout(height='420px'))